# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - Az-Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.13' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Export requirements for Azure remote build
        run: |
          uv lock
          uv export --format requirements.txt --no-hashes --output-file requirements.txt
     
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7A0FA4F0FB6F43C7A5297DF375E4DA63 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DAFD6B3FD8F245E290C287CE1B109908 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8E50310740C341FBB19CC7C5E7F88DDB }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'Az-Demo'
          slot-name: 'Production'
          package: '.'
          sku: flexconsumption
          remote-build: true
          respect-funcignore: true
          
